# Generated by Django 2.2.5 on 2019-09-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=120)),
                ('middleInitial', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sampleType', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('quality', models.CharField(max_length=25)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('referenceBase', models.CharField(max_length=10)),
                ('altrenativeBase', models.CharField(max_length=10)),
                ('geneName', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('mutationType', models.CharField(max_length=10)),
                ('alleleFrequency', models.DecimalField(decimal_places=20, max_digits=40)),
                ('sampleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Sample')),
            ],
        ),
    ]
