# Generated by Django 2.2.5 on 2019-09-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='altrenativeBase',
            new_name='alternativeBase',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='referenceBase',
            new_name='reference_base',
        ),
    ]
