# Generated by Django 2.2.5 on 2019-09-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20190928_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(default='', max_length=20),
        ),
    ]
