# Generated by Django 2.2.5 on 2019-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateOfDiagnosis',
            field=models.CharField(default='', max_length=20),
        ),
    ]
